[package]
name = "motionvm-forth"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "The Forth virtual machine that runs MOTION's compiled script modules"

[dependencies]
motionvm-formats.workspace = true

[lints]
workspace = true
